/* TIE Tech Tree — data
 *
 * Transcribed from "TIE Tech Tree v8" by u/GuderianX (r/StarWarsShips):
 * https://www.reddit.com/r/StarWarsShips/comments/1vlkb5i/tie_tech_tree_v8/
 *
 * status: 'both' = Canon and EU · 'canon' = just Canon · 'legends' = just EU (Legends) · 'hub' = annotation node
 * dl / dc: Legends / Canon date as written on the original chart (dates are the
 *          chart author's approximations, often from a ship's first battle).
 * wc / wl: Wookieepedia article paths (canon / Legends), verified against the
 *          MediaWiki API. search: fallback query when no article exists.
 * t: timeline position in years relative to the Battle of Yavin (negative = BBY).
 *    Ships whose date the chart lists as unknown/approximate are placed near
 *    their parent; the displayed date strings are always the chart's own.
 * row: vertical lane on the timeline. Group ships use explicit x/y instead.
 * type 'd' = direct development (solid) · 'l' = loose connection (dashed) · q = uncertain ("?")
 */
window.TIE_DATA = {
  nodes: [
    // ── Origins ─────────────────────────────────────────────
    { id: "starcourier", n: "Star Courier", st: "both", dl: "before 67 BBY",
      wc: "Star_Courier", wl: "Star_Courier/Legends", t: -67, row: 6 },
    { id: "eta2", n: "Eta-2 Actis Interceptor", st: "both", dl: "22 BBY",
      wc: "Eta-2_Actis-class_light_interceptor", t: -22, row: 5 },
    { id: "vwing", n: "Alpha-3 Nimbus-class V-wing starfighter", st: "both", dl: "19 BBY",
      wc: "Alpha-3_Nimbus-class_V-wing_starfighter", wl: "Alpha-3_Nimbus-class_V-wing_starfighter/Legends", t: -19, row: 5 },
    { id: "advproject", n: "Advanced Project Ship", st: "legends", dl: "before 29 BBY", fan: "concept art",
      wl: "Advanced_Project_ship", t: -29, row: 6 },
    { id: "tie_proto", n: "T.I.E. Starfighter", alt: "TIE fighter prototype", st: "both", dl: "~22 BBY",
      note: "Known in Legends as the T.I.E. starfighter and in Canon as the “TIE fighter prototype.” Canon note: Raith Sienar was inspired by the V-wing and Eta-2 Actis when designing the TIE/LN.",
      wc: "TIE_fighter_prototype", wl: "Twin_Ion_Engine_starfighter", t: -22, row: 6 },
    { id: "tie_sf", n: "TIE starfighter", st: "legends", dl: "~22 BBY",
      wl: "TIE_starfighter", t: -20.2, row: 6 },
    { id: "imp_proto", n: "Imperial starfighter prototype", st: "legends", dl: "~19 BBY",
      wl: "Imperial_starfighter_prototype", t: -19.5, row: 7 },
    { id: "infiltrator", n: "TIE Infiltrator", st: "legends", dl: "unknown", fan: "fan render",
      wl: "TIE_infiltrator", t: -14.5, row: 7 },

    // ── Main trunk ──────────────────────────────────────────
    { id: "tieln", n: "TIE/LN", st: "both", dl: "after 22 BBY", dc: "~18 BBY",
      wc: "TIE/ln_space_superiority_starfighter", wl: "TIE/ln_space_superiority_starfighter/Legends", t: -18, row: 6 },

    // ── TIE Advanced line ───────────────────────────────────
    { id: "adv_prototype", n: "TIE Advanced Prototype", st: "both", dl: "~4 BBY",
      wc: "TIE/ad_v1", t: -4.5, row: 4 },
    { id: "advx1", n: "TIE Advanced X1", st: "both", dl: "~3 BBY",
      wc: "TIE_Advanced_x1", wl: "TIE_Advanced_x1/Legends", t: -3, row: 4 },
    { id: "sentinel", n: "TIE Sentinel", st: "legends", dl: "unknown", fan: "concept sketch",
      wl: "TIE_Sentinel", t: -2.6, row: 3 },
    { id: "x1mod", n: "TIE Advanced X1 modified", st: "legends", dl: "after 0 ABY",
      wl: "TIE_Advanced_x1/Legends", t: 0.6, row: 3 },
    { id: "x1var", n: "TIE Advanced X1 variant", st: "legends", dl: "before 0 ABY", fan: "comic drawing",
      wl: "TIE_Advanced_x1/Legends", t: -0.7, row: 3 },
    { id: "avenger", n: "TIE Avenger", st: "both", dl: "after 3 ABY",
      wc: "TIE_Avenger_prototype", wl: "TIE/ad_starfighter", t: 3.5, row: 3 },
    { id: "advx2", n: "TIE Advanced X2", st: "legends", dl: "0 ABY",
      wl: "TIE/x2_starfighter", t: 0.3, row: 4 },
    { id: "advx3", n: "TIE Advanced X3", st: "legends", dl: "2 ABY", fan: "fan render",
      wl: "TIE/x3_starfighter", t: 2, row: 4 },
    { id: "advx7", n: "TIE Advanced X7", st: "both", dl: "~3 ABY",
      wc: "TIE_Advanced_x7", wl: "TIE_Advanced_x7/Legends", t: 3.2, row: 4 },
    { id: "defender", n: "TIE Defender", st: "both", dl: "~4 ABY",
      wc: "TIE/d_%22Defender%22_Multi-Role_Starfighter", wl: "TIE/d_%22Defender%22_Multi-Role_Starfighter/Legends", t: 4.6, row: 4 },
    { id: "redstar1", n: "Red Star 1", st: "legends", dl: "after 4 ABY",
      wl: "Red_Star_1", t: 7.2, row: 4 },

    // ── Interceptor cluster ─────────────────────────────────
    { id: "interceptor", n: "TIE Interceptor", st: "both", dl: "~0 ABY", fan: "fan render",
      note: "One reading holds the Interceptor might better descend from the X3, since the X3 lacks a hyperdrive and its hullform was more consistent with the TIE fighter — a downgrade that would only make sense as the start of a new series.",
      wc: "TIE/IN_interceptor", wl: "TIE/IN_interceptor/Legends", t: 0.3, row: 2 },
    { id: "crimson", n: "Crimson Squadron Interceptor", st: "legends", dl: "before 4 ABY",
      wl: "Unidentified_crimson_TIE/IN_interceptor_variant", t: 3.6, row: 1 },
    { id: "m3", n: "TIE Experimental M3", st: "legends", dl: "~3 ABY",
      wl: "TIE_Experimental_M3", t: 3, row: 0 },
    { id: "royal_guard", n: "TIE Interceptor Royal Guard", st: "both", dl: "after 0 ABY",
      wc: "Emperor's_Royal_Guard_TIE/IN_starfighter", t: 1.2, row: 0 },
    { id: "starhunter", n: "TIE Starhunter", st: "legends", dl: "~41 ABY", fan: "fan render",
      wl: "Starhunter", t: 41, row: 1 },

    // ── Legacy era (127+ ABY) ───────────────────────────────
    { id: "predator", n: "Predator-class fighter", st: "legends", dl: "~127 ABY",
      wl: "Predator-class_fighter", t: 126.5, row: 2 },
    { id: "neutralizer", n: "Neutralizer Class Bomber", st: "legends", dl: "~127 ABY",
      note: "Dating quirk: the Neutralizer is officially a modified Predator-class, but the Predator is noted as introduced in 130 ABY while the Neutralizer is noted as first used in 127 ABY.",
      wl: "Neutralizer-class_bomber", t: 127.5, row: 1 },
    { id: "sith_imp", n: "Sith-Imperial starfighter", st: "legends", dl: "137 ABY",
      wl: "Sith-Imperial_starfighter", t: 137, row: 0 },

    // ── Defender offshoots / Imperial Classified Flight Yards ──
    { id: "yards", n: "Imperial Classified Flight Yards", st: "hub",
      note: "A testing center where these advanced TIEs were evaluated in 0 BBY under Soontir Fel.", t: -0.15, row: 14 },
    { id: "hunter", n: "TIE Hunter", st: "legends", dl: "~1 BBY",
      wl: "TIE/hu_%22Hunter%22_Multi-Role_Starfighter", t: -1.5, row: 15 },
    { id: "aggressor", n: "TIE Aggressor", st: "both", dl: "before 0 BBY",
      wc: "TIE/ag_%22Aggressor%22_Starfighter", wl: "TIE/ag_%22Aggressor%22_Starfighter/Legends", t: -1, row: 16 },
    { id: "reaper", n: "TIE Reaper", st: "canon",
      wc: "TIE/rp_Reaper_attack_lander", t: 0.4, row: 15 },
    { id: "striker", n: "TIE Striker", st: "canon",
      wc: "TIE/sk_x1_experimental_air_superiority_fighter", t: 0.6, row: 16 },
    { id: "dagger", n: "Dagger-class starfighter", st: "legends", dl: "~32 BBY",
      wl: "Dagger-class_starfighter", t: -32, row: 14 },
    { id: "v38", n: "V38 Assault fighter", st: "legends", dl: "before 0 BBY",
      wl: "V38_assault_fighter", t: -1.1, row: 14 },
    { id: "phantom", n: "TIE Phantom", st: "both", dl: "before 0 BBY",
      wc: "TIE/ph_%22Phantom%22_Multi-Role_Stealth_Starfighter", wl: "TIE/ph_%22Phantom%22_Multi-Role_Stealth_Starfighter/Legends", t: -0.4, row: 15 },

    // ── TIE/LN comb — left column ───────────────────────────
    { id: "m1", n: "TIE Experimental M1", st: "legends", dl: "~3 ABY",
      wl: "TIE_Experimental_M1", t: 3, row: 11 },
    { id: "m2", n: "TIE Experimental M2", st: "legends", dl: "~3 ABY",
      wl: "TIE_Experimental_M2", t: 3.6, row: 12 },
    { id: "m5", n: "TIE Experimental M5", st: "legends", dl: "~3 ABY",
      wl: "TIE_Experimental_M5", t: 3.1, row: 13 },
    { id: "oppressor", n: "TIE Oppressor", st: "legends", dl: "after 0 ABY",
      wl: "TIE_Oppressor", t: 0.8, row: 13 },
    { id: "automated", n: "TIE automated fighter", st: "both", dl: "~10 ABY",
      wl: "TIE/D_automated_starfighter", t: 10, row: 11 },
    { id: "vulture", n: "Vulture-class Starfighter", st: "both",
      note: "Droid starfighters of the Clone Wars were the basis for the TIE/D.",
      wc: "Vulture-class_starfighter", wl: "Vulture-class_starfighter/Legends", t: -21, row: 11 },
    { id: "raptor", n: "TIE Raptor", st: "legends", dl: "after 4 ABY",
      wl: "TIE/rpt_starfighter", t: 5.4, row: 12 },
    { id: "vigilant", n: "TIE Vigilant", st: "both", dl: "~4 ABY",
      note: "Technically canon — it's based on the Kenner toys used in Return of the Jedi.",
      search: "TIE Vigilant", t: 4.4, row: 13 },
    { id: "mining_guild", n: "Mining Guild TIE", st: "canon", dc: "before 3 BBY",
      wc: "TIE/mg_Mining_Guild_starfighter", t: -3.4, row: 11 },
    { id: "sentry", n: "TIE Sentry", st: "legends",
      note: "From a manga adaptation of A New Hope.",
      search: "TIE Sentry", t: -0.4, row: 12 },
    { id: "iden", n: "Iden Versio's TIE/LN", st: "canon", dc: "before 4 BBY",
      wc: "Iden_Versio", t: -4.4, row: 13 },

    // ── TIE/LN comb — right column ──────────────────────────
    { id: "light_duty", n: "TIE Light Duty", st: "legends", dl: "unknown",
      wl: "TIE_Light_Duty", t: -11.5, row: 7 },
    { id: "super_tieln", n: "Super TIE/LN starfighter", st: "legends", dl: "after 19 BBY",
      wl: "Super_TIE/LN_starfighter", t: -17.2, row: 7 },
    { id: "fire_control", n: "TIE Fire Control", st: "both", dl: "unknown",
      wl: "TIE/fc_starfighter", t: -12.5, row: 5 },
    { id: "brute", n: "TIE Brute", st: "canon", dc: "before 10 BBY",
      wc: "TIE/rb_heavy_starfighter", t: -10.5, row: 12 },
    { id: "stealth", n: "TIE Stealth", st: "legends", dl: "~23 ABY", fan: "fan render",
      wl: "TIE_stealth", t: 23, row: 11 },
    { id: "scoutship", n: "Scout Ship", st: "both", dl: "before 9 ABY",
      note: "Possibly a later version of the TIE/rc.",
      wl: "Scout_ship_(TIE_model)", t: 8.6, row: 12 },
    { id: "tie_recon", n: "TIE Reconnaissance", st: "both", dl: "before 2 BBY",
      wl: "TIE/rc_starfighter", t: -2.3, row: 13 },
    { id: "vanguard", n: "TIE Vanguard", st: "legends", dl: "after 2 BBY",
      wl: "TIE/rc_vanguard", t: -0.6, row: 13 },
    { id: "tie_scout", n: "TIE Scout", st: "both", dl: "before 19 BBY",
      wl: "TIE_scout", t: -19.5, row: 12 },
    { id: "lone_scout", n: "Lone Scout-A", st: "legends", dl: "before 19 BBY",
      note: "Civilian variant of the TIE/sr. *Produced by Republic Sienar Systems.",
      wl: "Lone_Scout-A", t: -18.7, row: 13 },
    { id: "outland", n: "Outland TIE Fighter", st: "canon", dc: "after 4 ABY",
      wc: "Outland_TIE_fighter", t: 7, row: 13 },
    { id: "gable", n: "Gable Karius' TIE", st: "canon", dc: "~1 ABY",
      wc: "Gable_Karius", t: 1.2, row: 12 },

    // ── Bomber line ─────────────────────────────────────────
    { id: "ground_target", n: "TIE Ground Target", st: "both", dl: "~19 BBY",
      wl: "TIE/gt_starfighter", t: -19, row: 8 },
    { id: "sa_bomber", n: "TIE/sa Bomber", st: "both", dl: "~12 BBY",
      wc: "TIE/sa_tactical_bomber", wl: "TIE/sa_tactical_bomber/Legends", t: -12, row: 8 },
    { id: "heavy_bomber", n: "TIE Heavy Bomber", st: "legends", dl: "unknown",
      wl: "TIE_Heavy_Bomber", t: -8, row: 8 },
    { id: "interdictor", n: "TIE Interdictor/Punisher", st: "both", dl: "after 0 ABY",
      wc: "TIE/ca_%22Punisher%22_Starfighter", wl: "TIE/ca_Punisher/Legends", t: 0.7, row: 8 },
    { id: "mark2", n: "TIE Bomber Mark 2", st: "legends",
      note: "Only proposed — never produced.",
      wl: "TIE_Bomber_Mark_2", t: 2.2, row: 8 },
    { id: "scimitar_ab", n: "Scimitar assault bomber", st: "legends", dl: "after 8 ABY",
      wl: "Scimitar_assault_bomber", t: 8.4, row: 8 },
    { id: "scimitar2", n: "Scimitar Mark II", st: "legends", dl: "unknown",
      wl: "Scimitar_Mark_II", t: 12, row: 8 },
    { id: "terror", n: "TIE Terror (Shadow Squad TIE)", st: "legends", dl: "before 1 BBY",
      search: "TIE Terror Shadow Squad", t: -2, row: 9 },
    { id: "shuttle", n: "TIE Shuttle", st: "both", dl: "before 0 BBY",
      wc: "TIE/sh_VIP_shuttle", t: -0.3, row: 9 },
    { id: "boarding", n: "TIE Boarding Shuttle/Craft", st: "both", dl: "before 0 BBY",
      wc: "TIE/br_boarding_shuttle", wl: "TIE_boarding_craft", t: -0.8, row: 10 },
    { id: "lander", n: "TIE Lander", st: "both", dl: "unknown",
      wc: "TIE_lander", wl: "TIE_lander/Legends", t: 0.4, row: 10 },
    { id: "itt", n: "TIE Imperial Troop Transport", st: "legends", dl: "before 3 ABY", fan: "fan render",
      search: "TIE Imperial Troop Transport", t: 2.6, row: 10 },
    { id: "m4", n: "TIE Experimental M4", st: "legends", dl: "~3 ABY",
      wl: "TIE_Experimental_M4", t: 3, row: 9 },
    { id: "gand", n: "Gand Starfighter", st: "legends", dl: "before 7 ABY", fan: "fan render",
      wl: "Gand_starfighter", t: 6.6, row: 9 },
    { id: "lancet", n: "Lancet Aerial Artillery", st: "legends", dl: "unknown",
      note: "A blending of the TIE/sa Bomber with the Lambda shuttle.",
      wl: "Lancet_Aerial_Artillery", t: 5, row: 10 },
    { id: "recon_fighter", n: "TIE Reconnaissance Fighter", st: "both", dl: "before 40 ABY",
      wl: "TIE_Reconnaissance_Fighter", t: 39.5, row: 9 },

    // ── Non-Starfighters ────────────────────────────────────
    { id: "crawler", n: "TIE Crawler", st: "legends",
      note: "Uses parts of the TIE/LN.", g: "Non-Starfighters",
      wl: "TIE_crawler", x: 700, y: 3650 },
    { id: "mauler", n: "TIE Mauler", st: "legends",
      note: "Uses parts of the TIE/LN.", g: "Non-Starfighters",
      wl: "TIE_ap-1", x: 1000, y: 3650 },
    { id: "fighter_boat", n: "TIE Fighter Boat", st: "legends", fan: "fan render",
      note: "Uses parts of the TIE/sa Bomber.", g: "Non-Starfighters",
      wl: "TIE_fighter_boat", x: 700, y: 3820 },
    { id: "subfighter", n: "TIE Subfighter", st: "legends",
      note: "No reliable image of this craft exists.", g: "Non-Starfighters",
      wl: "TIE_Subfighter", x: 1000, y: 3820 },

    // ── Not clearly belonging to any other lines ────────────
    { id: "clawcraft", n: "Nsiss Clawcraft", st: "legends",
      note: "Only related to the TIE series, not actually part of it.", g: "Unplaced",
      wl: "Nssis-class_Clawcraft", x: 1600, y: 3650 },
    { id: "aleph", n: "Aleph-class starfighter", st: "legends",
      note: "Sort of related to the TIE series.", g: "Unplaced",
      wl: "Aleph-class_starfighter", x: 1900, y: 3650 },
    { id: "clutch", n: "Clutch Fighter", st: "legends", fan: "unofficial",
      note: "An “Ugly” using a TIE/LN cockpit with three triangular fins.", g: "Unplaced",
      wl: "Clutch_(fighter)", x: 1750, y: 3820 }
  ],

  edges: [
    // origins
    { f: "eta2", t: "tie_proto", type: "l" },
    { f: "vwing", t: "tie_proto", type: "l" },
    { f: "starcourier", t: "advproject", type: "d", q: 1 },
    { f: "advproject", t: "tie_proto", type: "d" },
    { f: "imp_proto", t: "tie_proto", type: "d" },
    { f: "tie_proto", t: "tie_sf", type: "d", q: 1 },
    { f: "tie_sf", t: "tieln", type: "d" },
    { f: "tie_proto", t: "infiltrator", type: "d", q: 1 },
    { f: "starcourier", t: "adv_prototype", type: "d" },

    // Advanced line
    { f: "tieln", t: "adv_prototype", type: "d" },
    { f: "adv_prototype", t: "advx1", type: "d" },
    { f: "advx1", t: "sentinel", type: "d" },
    { f: "advx1", t: "x1mod", type: "d" },
    { f: "advx1", t: "x1var", type: "d" },
    { f: "advx1", t: "avenger", type: "d" },
    { f: "advx1", t: "advx2", type: "d", q: 1 },
    { f: "advx2", t: "advx3", type: "d", q: 1 },
    { f: "advx3", t: "advx7", type: "d" },
    { f: "advx7", t: "defender", type: "d" },
    { f: "defender", t: "redstar1", type: "d" },

    // Interceptor cluster
    { f: "advx1", t: "interceptor", type: "d", q: 1,
      note: "Origin usually given as the TIE Advanced X1 line." },
    { f: "interceptor", t: "royal_guard", type: "d" },
    { f: "interceptor", t: "crimson", type: "d" },
    { f: "interceptor", t: "m3", type: "d" },
    { f: "interceptor", t: "starhunter", type: "d", q: 1 },
    { f: "starhunter", t: "predator", type: "d" },
    { f: "predator", t: "neutralizer", type: "d" },
    { f: "predator", t: "sith_imp", type: "d" },

    // Defender offshoots via the Classified Flight Yards
    { f: "defender", t: "yards", type: "l", q: 1 },
    { f: "yards", t: "hunter", type: "l" },
    { f: "yards", t: "aggressor", type: "l" },
    { f: "yards", t: "phantom", type: "l" },
    { f: "yards", t: "reaper", type: "l", q: 1 },
    { f: "yards", t: "striker", type: "l", q: 1 },
    { f: "dagger", t: "v38", type: "d" },
    { f: "v38", t: "phantom", type: "d" },

    // TIE/LN comb — left
    { f: "tieln", t: "m1", type: "d" },
    { f: "tieln", t: "m2", type: "d" },
    { f: "tieln", t: "m5", type: "d" },
    { f: "tieln", t: "oppressor", type: "d" },
    { f: "tieln", t: "automated", type: "d" },
    { f: "vulture", t: "automated", type: "l",
      note: "Droid starfighters of the Clone Wars were the basis for the TIE/D." },
    { f: "tieln", t: "raptor", type: "d" },
    { f: "tieln", t: "vigilant", type: "d" },
    { f: "tieln", t: "mining_guild", type: "d", q: 1 },
    { f: "tieln", t: "sentry", type: "d", q: 1 },
    { f: "tieln", t: "iden", type: "d", q: 1 },

    // TIE/LN comb — right
    { f: "tieln", t: "ground_target", type: "d" },
    { f: "tieln", t: "light_duty", type: "d" },
    { f: "tieln", t: "super_tieln", type: "d" },
    { f: "tieln", t: "fire_control", type: "d" },
    { f: "tieln", t: "brute", type: "d" },
    { f: "tieln", t: "stealth", type: "d", q: 1 },
    { f: "tieln", t: "scoutship", type: "d" },
    { f: "tieln", t: "tie_recon", type: "d" },
    { f: "tie_recon", t: "vanguard", type: "d" },
    { f: "tieln", t: "tie_scout", type: "l", q: 1 },
    { f: "tie_scout", t: "lone_scout", type: "d" },
    { f: "tieln", t: "outland", type: "d", q: 1 },
    { f: "tieln", t: "gable", type: "d", q: 1 },

    // Bomber line
    { f: "ground_target", t: "sa_bomber", type: "d" },
    { f: "sa_bomber", t: "heavy_bomber", type: "d" },
    { f: "heavy_bomber", t: "interdictor", type: "d" },
    { f: "heavy_bomber", t: "terror", type: "d" },
    { f: "interdictor", t: "mark2", type: "d", q: 1 },
    { f: "mark2", t: "scimitar_ab", type: "d" },
    { f: "scimitar_ab", t: "scimitar2", type: "d", q: 1 },
    { f: "sa_bomber", t: "shuttle", type: "d" },
    { f: "sa_bomber", t: "boarding", type: "d" },
    { f: "boarding", t: "lander", type: "d" },
    { f: "boarding", t: "itt", type: "d" },
    { f: "sa_bomber", t: "m4", type: "d" },
    { f: "sa_bomber", t: "gand", type: "d", q: 1 },
    { f: "sa_bomber", t: "lancet", type: "l" },
    { f: "sa_bomber", t: "recon_fighter", type: "d", q: 1 }
  ],

  groups: [
    { label: "Non-Starfighters", x: 1750, y: 3820 },
    { label: "Not clearly belonging to any other lines", x: 1750, y: 3820 }
  ]
};
