/* TIE Tech Tree — data
 *
 * Transcribed from "TIE Tech Tree v8" by u/GuderianX (r/StarWarsShips):
 * https://www.reddit.com/r/StarWarsShips/comments/1vlkb5i/tie_tech_tree_v8/
 *
 * status: 'both' = Canon and EU · 'canon' = just Canon · 'legends' = just EU (Legends) · 'hub' = annotation node
 * dl / dc: Legends / Canon date as written on the original chart (dates are the
 *          chart author's approximations, often from a ship's first battle).
 * wc / wl: Wookieepedia article paths (canon / Legends), verified against the
 *          MediaWiki API. search: fallback query when no article exists.
 * type 'd' = direct development (solid) · 'l' = loose connection (dashed) · q = uncertain ("?")
 */
window.TIE_DATA = {
  nodes: [
    // ── Origins ─────────────────────────────────────────────
    { id: "starcourier", n: "Star Courier", st: "both", dl: "before 67 BBY",
      wc: "Star_Courier", wl: "Star_Courier/Legends", x: 140, y: 760 },
    { id: "eta2", n: "Eta-2 Actis Interceptor", st: "both", dl: "22 BBY",
      wc: "Eta-2_Actis-class_light_interceptor", x: 480, y: 470 },
    { id: "vwing", n: "Alpha-3 Nimbus-class V-wing starfighter", st: "both", dl: "19 BBY",
      wc: "Alpha-3_Nimbus-class_V-wing_starfighter", wl: "Alpha-3_Nimbus-class_V-wing_starfighter/Legends", x: 850, y: 470 },
    { id: "advproject", n: "Advanced Project Ship", st: "legends", dl: "before 29 BBY", fan: "concept art",
      wl: "Advanced_Project_ship", x: 420, y: 760 },
    { id: "tie_proto", n: "T.I.E. Starfighter", alt: "TIE fighter prototype", st: "both", dl: "~22 BBY",
      note: "Green Legends name with the blue Canon name “TIE fighter prototype” on the original chart. Canon note: Raith Sienar was inspired by the V-wing and Eta-2 Actis when designing the TIE/LN.",
      wc: "TIE_fighter_prototype", wl: "Twin_Ion_Engine_starfighter", x: 700, y: 760 },
    { id: "tie_sf", n: "TIE starfighter", st: "legends", dl: "~22 BBY",
      wl: "TIE_starfighter", x: 980, y: 760 },
    { id: "imp_proto", n: "Imperial starfighter prototype", st: "legends", dl: "~19 BBY",
      wl: "Imperial_starfighter_prototype", x: 380, y: 980 },
    { id: "infiltrator", n: "TIE Infiltrator", st: "legends", dl: "unknown", fan: "fan render",
      wl: "TIE_infiltrator", x: 760, y: 1000 },

    // ── Main trunk ──────────────────────────────────────────
    { id: "tieln", n: "TIE/LN", st: "both", dl: "after 22 BBY", dc: "~18 BBY",
      wc: "TIE/ln_space_superiority_starfighter", wl: "TIE/ln_space_superiority_starfighter/Legends", x: 1260, y: 760 },

    // ── TIE Advanced line ───────────────────────────────────
    { id: "adv_prototype", n: "TIE Advanced Prototype", st: "both", dl: "~4 BBY",
      wc: "TIE/ad_v1", x: 1540, y: 620 },
    { id: "advx1", n: "TIE Advanced X1", st: "both", dl: "~3 BBY",
      wc: "TIE_Advanced_x1", wl: "TIE_Advanced_x1/Legends", x: 1820, y: 560 },
    { id: "sentinel", n: "TIE Sentinel", st: "legends", dl: "unknown", fan: "concept sketch",
      wl: "TIE_Sentinel", x: 1700, y: 170 },
    { id: "x1mod", n: "TIE Advanced X1 modified", st: "legends", dl: "after 0 ABY",
      wl: "TIE_Advanced_x1/Legends", x: 1650, y: 300 },
    { id: "x1var", n: "TIE Advanced X1 variant", st: "legends", dl: "before 0 ABY", fan: "comic drawing",
      wl: "TIE_Advanced_x1/Legends", x: 1580, y: 430 },
    { id: "avenger", n: "TIE Avenger", st: "both", dl: "after 3 ABY",
      wc: "TIE_Avenger_prototype", wl: "TIE/ad_starfighter", x: 2070, y: 430 },
    { id: "advx2", n: "TIE Advanced X2", st: "legends", dl: "0 ABY",
      wl: "TIE/x2_starfighter", x: 2100, y: 560 },
    { id: "advx3", n: "TIE Advanced X3", st: "legends", dl: "2 ABY", fan: "fan render",
      wl: "TIE/x3_starfighter", x: 2360, y: 560 },
    { id: "advx7", n: "TIE Advanced X7", st: "both", dl: "~3 ABY",
      wc: "TIE_Advanced_x7", wl: "TIE_Advanced_x7/Legends", x: 2620, y: 560 },
    { id: "defender", n: "TIE Defender", st: "both", dl: "~4 ABY",
      wc: "TIE/d_%22Defender%22_Multi-Role_Starfighter", wl: "TIE/d_%22Defender%22_Multi-Role_Starfighter/Legends", x: 2880, y: 620 },
    { id: "redstar1", n: "Red Star 1", st: "legends", dl: "after 4 ABY",
      wl: "Red_Star_1", x: 3140, y: 680 },

    // ── Interceptor cluster ─────────────────────────────────
    { id: "interceptor", n: "TIE Interceptor", st: "both", dl: "~0 ABY", fan: "fan render",
      note: "Chart author's note: “Description wise it would make more sense if the Interceptor was a variant of the X3, since the X3 doesn't have Hyperdrive and its hullform was more consistent with the TIE fighter. That downgrade would only make sense as a start of a new series.”",
      wc: "TIE/IN_interceptor", wl: "TIE/IN_interceptor/Legends", x: 2340, y: 300 },
    { id: "crimson", n: "Crimson Squadron Interceptor", st: "legends", dl: "before 4 ABY",
      wl: "Unidentified_crimson_TIE/IN_interceptor_variant", x: 2120, y: 170 },
    { id: "m3", n: "TIE Experimental M3", st: "legends", dl: "~3 ABY",
      wl: "TIE_Experimental_M3", x: 2560, y: 170 },
    { id: "royal_guard", n: "TIE Interceptor Royal Guard", st: "both", dl: "after 0 ABY",
      wc: "Emperor's_Royal_Guard_TIE/IN_starfighter", x: 2340, y: 60 },
    { id: "starhunter", n: "TIE Starhunter", st: "legends", dl: "~41 ABY", fan: "fan render",
      wl: "Starhunter", x: 2650, y: 300 },

    // ── Legacy era (127+ ABY) ───────────────────────────────
    { id: "predator", n: "Predator-class fighter", st: "legends", dl: "~127 ABY",
      wl: "Predator-class_fighter", x: 2940, y: 300 },
    { id: "neutralizer", n: "Neutralizer Class Bomber", st: "legends", dl: "~127 ABY",
      note: "Chart author's note: the Neutralizer is officially a modified Predator-class, but the Predator is noted as introduced in 130 ABY while the Neutralizer is noted as first used in 127 ABY.",
      wl: "Neutralizer-class_bomber", x: 2940, y: 170 },
    { id: "sith_imp", n: "Sith-Imperial starfighter", st: "legends", dl: "137 ABY",
      wl: "Sith-Imperial_starfighter", x: 2940, y: 60 },

    // ── Defender offshoots / Imperial Classified Flight Yards ──
    { id: "yards", n: "Imperial Classified Flight Yards", st: "hub",
      note: "A testing center in which all of these were tested in 0 BBY by Soontir Fel (per the original chart).", x: 2960, y: 860 },
    { id: "hunter", n: "TIE Hunter", st: "legends", dl: "~1 BBY",
      wl: "TIE/hu_%22Hunter%22_Multi-Role_Starfighter", x: 3260, y: 780 },
    { id: "aggressor", n: "TIE Aggressor", st: "both", dl: "before 0 BBY",
      wc: "TIE/ag_%22Aggressor%22_Starfighter", wl: "TIE/ag_%22Aggressor%22_Starfighter/Legends", x: 3260, y: 900 },
    { id: "reaper", n: "TIE Reaper", st: "canon",
      wc: "TIE/rp_Reaper_attack_lander", x: 3260, y: 1030 },
    { id: "striker", n: "TIE Striker", st: "canon",
      wc: "TIE/sk_x1_experimental_air_superiority_fighter", x: 3260, y: 1150 },
    { id: "dagger", n: "Dagger-class starfighter", st: "legends", dl: "~32 BBY",
      wl: "Dagger-class_starfighter", x: 2500, y: 1310 },
    { id: "v38", n: "V38 Assault fighter", st: "legends", dl: "before 0 BBY",
      wl: "V38_assault_fighter", x: 2780, y: 1310 },
    { id: "phantom", n: "TIE Phantom", st: "both", dl: "before 0 BBY",
      wc: "TIE/ph_%22Phantom%22_Multi-Role_Stealth_Starfighter", wl: "TIE/ph_%22Phantom%22_Multi-Role_Stealth_Starfighter/Legends", x: 3060, y: 1310 },

    // ── TIE/LN comb — left column ───────────────────────────
    { id: "m1", n: "TIE Experimental M1", st: "legends", dl: "~3 ABY",
      wl: "TIE_Experimental_M1", x: 990, y: 910 },
    { id: "m2", n: "TIE Experimental M2", st: "legends", dl: "~3 ABY",
      wl: "TIE_Experimental_M2", x: 990, y: 1030 },
    { id: "m5", n: "TIE Experimental M5", st: "legends", dl: "~3 ABY",
      wl: "TIE_Experimental_M5", x: 990, y: 1150 },
    { id: "oppressor", n: "TIE Oppressor", st: "legends", dl: "after 0 ABY",
      wl: "TIE_Oppressor", x: 990, y: 1270 },
    { id: "automated", n: "TIE automated fighter", st: "both", dl: "~10 ABY",
      wl: "TIE/D_automated_starfighter", x: 990, y: 1390 },
    { id: "vulture", n: "Vulture-class Starfighter", st: "both",
      note: "Droid starfighters of the Clone Wars were the basis for the TIE/D (per the original chart).",
      wc: "Vulture-class_starfighter", wl: "Vulture-class_starfighter/Legends", x: 620, y: 1390 },
    { id: "raptor", n: "TIE Raptor", st: "legends", dl: "after 4 ABY",
      wl: "TIE/rpt_starfighter", x: 990, y: 1510 },
    { id: "vigilant", n: "TIE Vigilant", st: "both", dl: "~4 ABY",
      note: "Technically canon — it's based on the Kenner toys used in Return of the Jedi (per the original chart).",
      search: "TIE Vigilant", x: 990, y: 1630 },
    { id: "mining_guild", n: "Mining Guild TIE", st: "canon", dc: "before 3 BBY",
      wc: "TIE/mg_Mining_Guild_starfighter", x: 990, y: 1750 },
    { id: "sentry", n: "TIE Sentry", st: "legends",
      note: "From a manga adaptation of A New Hope (per the original chart).",
      search: "TIE Sentry", x: 990, y: 1870 },
    { id: "iden", n: "Iden Versio's TIE/LN", st: "canon", dc: "before 4 BBY",
      wc: "Iden_Versio", x: 990, y: 1990 },

    // ── TIE/LN comb — right column ──────────────────────────
    { id: "light_duty", n: "TIE Light Duty", st: "legends", dl: "unknown",
      wl: "TIE_Light_Duty", x: 1530, y: 1030 },
    { id: "super_tieln", n: "Super TIE/LN starfighter", st: "legends", dl: "after 19 BBY",
      wl: "Super_TIE/LN_starfighter", x: 1530, y: 1150 },
    { id: "fire_control", n: "TIE Fire Control", st: "both", dl: "unknown",
      wl: "TIE/fc_starfighter", x: 1530, y: 1270 },
    { id: "brute", n: "TIE Brute", st: "canon", dc: "before 10 BBY",
      wc: "TIE/rb_heavy_starfighter", x: 1530, y: 1390 },
    { id: "stealth", n: "TIE Stealth", st: "legends", dl: "~23 ABY", fan: "fan render",
      wl: "TIE_stealth", x: 1530, y: 1510 },
    { id: "scoutship", n: "Scout Ship", st: "both", dl: "before 9 ABY",
      note: "Possibly a later version of the TIE/rc (per the original chart).",
      wl: "Scout_ship_(TIE_model)", x: 1530, y: 1630 },
    { id: "tie_recon", n: "TIE Reconnaissance", st: "both", dl: "before 2 BBY",
      wl: "TIE/rc_starfighter", x: 1530, y: 1750 },
    { id: "vanguard", n: "TIE Vanguard", st: "legends", dl: "after 2 BBY",
      wl: "TIE/rc_vanguard", x: 1810, y: 1750 },
    { id: "tie_scout", n: "TIE Scout", st: "both", dl: "before 19 BBY",
      wl: "TIE_scout", x: 1530, y: 1870 },
    { id: "lone_scout", n: "Lone Scout-A", st: "legends", dl: "before 19 BBY",
      note: "Civilian variant of the TIE/sr. *Produced by Republic Sienar Systems.",
      wl: "Lone_Scout-A", x: 1810, y: 1870 },
    { id: "outland", n: "Outland TIE Fighter", st: "canon", dc: "after 4 ABY",
      wc: "Outland_TIE_fighter", x: 1530, y: 1990 },
    { id: "gable", n: "Gable Karius' TIE", st: "canon", dc: "~1 ABY",
      wc: "Gable_Karius", x: 1530, y: 2110 },

    // ── Bomber line ─────────────────────────────────────────
    { id: "ground_target", n: "TIE Ground Target", st: "both", dl: "~19 BBY",
      wl: "TIE/gt_starfighter", x: 1530, y: 910 },
    { id: "sa_bomber", n: "TIE/sa Bomber", st: "both", dl: "~12 BBY",
      wc: "TIE/sa_tactical_bomber", wl: "TIE/sa_tactical_bomber/Legends", x: 1810, y: 910 },
    { id: "heavy_bomber", n: "TIE Heavy Bomber", st: "legends", dl: "unknown",
      wl: "TIE_Heavy_Bomber", x: 2090, y: 910 },
    { id: "interdictor", n: "TIE Interdictor/Punisher", st: "both", dl: "after 0 ABY",
      wc: "TIE/ca_%22Punisher%22_Starfighter", wl: "TIE/ca_Punisher/Legends", x: 2370, y: 910 },
    { id: "mark2", n: "TIE Bomber Mark 2", st: "legends",
      note: "Only proposed — never produced (per the original chart).",
      wl: "TIE_Bomber_Mark_2", x: 2650, y: 910 },
    { id: "scimitar_ab", n: "Scimitar assault bomber", st: "legends", dl: "after 8 ABY",
      wl: "Scimitar_assault_bomber", x: 2650, y: 1040 },
    { id: "scimitar2", n: "Scimitar Mark II", st: "legends", dl: "unknown",
      wl: "Scimitar_Mark_II", x: 2650, y: 1170 },
    { id: "terror", n: "TIE Terror (Shadow Squad TIE)", st: "legends", dl: "before 1 BBY",
      search: "TIE Terror Shadow Squad", x: 2370, y: 1050 },
    { id: "shuttle", n: "TIE Shuttle", st: "both", dl: "before 0 BBY",
      wc: "TIE/sh_VIP_shuttle", x: 2090, y: 1120 },
    { id: "boarding", n: "TIE Boarding Shuttle/Craft", st: "both", dl: "before 0 BBY",
      wc: "TIE/br_boarding_shuttle", wl: "TIE_boarding_craft", x: 2090, y: 1240 },
    { id: "lander", n: "TIE Lander", st: "both", dl: "unknown",
      wc: "TIE_lander", wl: "TIE_lander/Legends", x: 2370, y: 1240 },
    { id: "itt", n: "TIE Imperial Troop Transport", st: "legends", dl: "before 3 ABY", fan: "fan render",
      search: "TIE Imperial Troop Transport", x: 2370, y: 1370 },
    { id: "m4", n: "TIE Experimental M4", st: "legends", dl: "~3 ABY",
      wl: "TIE_Experimental_M4", x: 2090, y: 1370 },
    { id: "gand", n: "Gand Starfighter", st: "legends", dl: "before 7 ABY", fan: "fan render",
      wl: "Gand_starfighter", x: 2090, y: 1490 },
    { id: "lancet", n: "Lancet Aerial Artillery", st: "legends", dl: "unknown",
      note: "A blending of the TIE/sa Bomber with the Lambda shuttle (per the original chart).",
      wl: "Lancet_Aerial_Artillery", x: 2090, y: 1610 },
    { id: "recon_fighter", n: "TIE Reconnaissance Fighter", st: "both", dl: "before 40 ABY",
      wl: "TIE_Reconnaissance_Fighter", x: 2090, y: 1730 },

    // ── Non-Starfighters ────────────────────────────────────
    { id: "crawler", n: "TIE Crawler", st: "legends",
      note: "Uses parts of the TIE/LN.", g: "Non-Starfighters",
      wl: "TIE_crawler", x: 560, y: 2280 },
    { id: "mauler", n: "TIE Mauler", st: "legends",
      note: "Uses parts of the TIE/LN.", g: "Non-Starfighters",
      wl: "TIE_ap-1", x: 830, y: 2280 },
    { id: "fighter_boat", n: "TIE Fighter Boat", st: "legends", fan: "fan render",
      note: "Uses parts of the TIE/sa Bomber.", g: "Non-Starfighters",
      wl: "TIE_fighter_boat", x: 560, y: 2420 },
    { id: "subfighter", n: "TIE Subfighter", st: "legends",
      note: "Shown on the original chart with a “?” in place of an image.", g: "Non-Starfighters",
      wl: "TIE_Subfighter", x: 830, y: 2420 },

    // ── Not clearly belonging to any other lines ────────────
    { id: "clawcraft", n: "Nsiss Clawcraft", st: "legends",
      note: "Only related to the TIE series, not actually part of it (per the original chart).", g: "Unplaced",
      wl: "Nssis-class_Clawcraft", x: 1400, y: 2280 },
    { id: "aleph", n: "Aleph-class starfighter", st: "legends",
      note: "Sort of related to the TIE series (per the original chart).", g: "Unplaced",
      wl: "Aleph-class_starfighter", x: 1680, y: 2280 },
    { id: "clutch", n: "Clutch Fighter", st: "legends", fan: "unofficial",
      note: "An “Ugly” using a TIE/LN cockpit with three triangular fins (per the original chart).", g: "Unplaced",
      wl: "Clutch_(fighter)", x: 1540, y: 2420 }
  ],

  edges: [
    // origins
    { f: "eta2", t: "tie_proto", type: "l" },
    { f: "vwing", t: "tie_proto", type: "l" },
    { f: "starcourier", t: "advproject", type: "d", q: 1 },
    { f: "advproject", t: "tie_proto", type: "d" },
    { f: "imp_proto", t: "tie_proto", type: "d" },
    { f: "tie_proto", t: "tie_sf", type: "d", q: 1 },
    { f: "tie_sf", t: "tieln", type: "d" },
    { f: "tie_proto", t: "infiltrator", type: "d", q: 1 },
    { f: "starcourier", t: "adv_prototype", type: "d" },

    // Advanced line
    { f: "tieln", t: "adv_prototype", type: "d" },
    { f: "adv_prototype", t: "advx1", type: "d" },
    { f: "advx1", t: "sentinel", type: "d" },
    { f: "advx1", t: "x1mod", type: "d" },
    { f: "advx1", t: "x1var", type: "d" },
    { f: "advx1", t: "avenger", type: "d" },
    { f: "advx1", t: "advx2", type: "d", q: 1 },
    { f: "advx2", t: "advx3", type: "d", q: 1 },
    { f: "advx3", t: "advx7", type: "d" },
    { f: "advx7", t: "defender", type: "d" },
    { f: "defender", t: "redstar1", type: "d" },

    // Interceptor cluster
    { f: "advx1", t: "interceptor", type: "d", q: 1,
      note: "Origin partially hidden on the original chart; usually given as the TIE Advanced X1 line." },
    { f: "interceptor", t: "royal_guard", type: "d" },
    { f: "interceptor", t: "crimson", type: "d" },
    { f: "interceptor", t: "m3", type: "d" },
    { f: "interceptor", t: "starhunter", type: "d", q: 1 },
    { f: "starhunter", t: "predator", type: "d" },
    { f: "predator", t: "neutralizer", type: "d" },
    { f: "predator", t: "sith_imp", type: "d" },

    // Defender offshoots via the Classified Flight Yards
    { f: "defender", t: "yards", type: "l", q: 1 },
    { f: "yards", t: "hunter", type: "l" },
    { f: "yards", t: "aggressor", type: "l" },
    { f: "yards", t: "phantom", type: "l" },
    { f: "yards", t: "reaper", type: "l", q: 1 },
    { f: "yards", t: "striker", type: "l", q: 1 },
    { f: "dagger", t: "v38", type: "d" },
    { f: "v38", t: "phantom", type: "d" },

    // TIE/LN comb — left
    { f: "tieln", t: "m1", type: "d" },
    { f: "tieln", t: "m2", type: "d" },
    { f: "tieln", t: "m5", type: "d" },
    { f: "tieln", t: "oppressor", type: "d" },
    { f: "tieln", t: "automated", type: "d" },
    { f: "vulture", t: "automated", type: "l",
      note: "Droid starfighters of the Clone Wars were the basis for the TIE/D." },
    { f: "tieln", t: "raptor", type: "d" },
    { f: "tieln", t: "vigilant", type: "d" },
    { f: "tieln", t: "mining_guild", type: "d", q: 1 },
    { f: "tieln", t: "sentry", type: "d", q: 1 },
    { f: "tieln", t: "iden", type: "d", q: 1 },

    // TIE/LN comb — right
    { f: "tieln", t: "ground_target", type: "d" },
    { f: "tieln", t: "light_duty", type: "d" },
    { f: "tieln", t: "super_tieln", type: "d" },
    { f: "tieln", t: "fire_control", type: "d" },
    { f: "tieln", t: "brute", type: "d" },
    { f: "tieln", t: "stealth", type: "d", q: 1 },
    { f: "tieln", t: "scoutship", type: "d" },
    { f: "tieln", t: "tie_recon", type: "d" },
    { f: "tie_recon", t: "vanguard", type: "d" },
    { f: "tieln", t: "tie_scout", type: "l", q: 1 },
    { f: "tie_scout", t: "lone_scout", type: "d" },
    { f: "tieln", t: "outland", type: "d", q: 1 },
    { f: "tieln", t: "gable", type: "d", q: 1 },

    // Bomber line
    { f: "ground_target", t: "sa_bomber", type: "d" },
    { f: "sa_bomber", t: "heavy_bomber", type: "d" },
    { f: "heavy_bomber", t: "interdictor", type: "d" },
    { f: "heavy_bomber", t: "terror", type: "d" },
    { f: "interdictor", t: "mark2", type: "d", q: 1 },
    { f: "mark2", t: "scimitar_ab", type: "d" },
    { f: "scimitar_ab", t: "scimitar2", type: "d", q: 1 },
    { f: "sa_bomber", t: "shuttle", type: "d" },
    { f: "sa_bomber", t: "boarding", type: "d" },
    { f: "boarding", t: "lander", type: "d" },
    { f: "boarding", t: "itt", type: "d" },
    { f: "sa_bomber", t: "m4", type: "d" },
    { f: "sa_bomber", t: "gand", type: "d", q: 1 },
    { f: "sa_bomber", t: "lancet", type: "l" },
    { f: "sa_bomber", t: "recon_fighter", type: "d", q: 1 }
  ],

  groups: [
    { label: "Non-Starfighters", x: 690, y: 2190 },
    { label: "Not clearly belonging to any other lines", x: 1540, y: 2190 }
  ]
};
